apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: sample-pipeline
spec:
  tasks:
  - name: foo
    taskRef:
      name: foo

  - name: slack-approval
    params:
    - name: slackChannel
      value: "#mad-roadshow-france-2023"
    - name: slackSecretName
      value: "tekton-tokens"
    - name: pipelineId
      value: "$(context.pipelineRun.name)"
    runAfter:
    - foo
    taskRef:
      name: slack-approval

  - name: bar
    taskRef:
      name: bar
    runAfter:
    - slack-approval
