apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: foo
spec:
  steps:
  - name: foo
    image: registry.access.redhat.com/ubi8/ubi:8.8
    script: |
      #!/bin/sh
      set -eu

      echo "FOO"

      exit 0
