apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: bar
spec:
  steps:
  - name: bar
    image: registry.access.redhat.com/ubi8/ubi:8.8
    script: |
      #!/bin/sh
      set -eu

      echo "BAR"

      exit 0
